[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bin-wise"
version = "0.1.0"
description = "ごみ分別します。"
dependencies = [
    "requests",
    "dataclasses; python_version < '3.12'"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.setuptools.packages.find]
where = ["src"]